baseURL = "https://gem-cp.github.io/recipes/"
languageCode = "de-de"
title = "Rezepte"
#canonifyURLs = true

enableGitInfo = true
enableGitInfoAuthor = true
enableGitInfoDate = true
enableGitInfoURL = true

# Theme als Modul importieren
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

# Sag Hugo, wo dein Inhalt und deine Bilder liegen
#contentDir = "content"
#staticDir = ["static"]

[outputs]
  home = ["HTML", "RSS", "JSON"] # Needed for search functionality

[params]
  author = "Christian Plagens"
  description = "Eine Sammlung meiner Lieblingsrezepte."
  defaultTheme = "auto" # "light", "dark" oder "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  #ShowToc = true
  #TocOpen = false
  EnableInstantClick = true

  [params.search]
    enable = true

  #[params.homeInfoParams]
  [params.profile]
    enable = true
    imageUrl = "/images/mein-profilbild.jpg" # Optional: Lade ein Bild nach /static/images/
    title = "Meine Rezeptsammlung"
    subtitle = "Herzlich willkommen! Hier findest du einfache und leckere Rezepte aus aller Welt. Viel Spaß beim Stöbern und Nachkochen."
  
    [[params.profile.buttons]]
      name = "Alle Rezepte"
      url = "/archives" # PaperMod hat eine eingebaute Archiv-Seite
    [[params.profile.buttons]]
      name = "Über mich"
      url = "/about" # Verlinkt zu deiner "about.md"

[taxonomies]
  tag = "tags"
  category = "categories"

# --- SPRACHEINSTELLUNGEN ---
[languages]
  [languages.de]
    contentDir = 'content/de'
    languageName = 'Deutsch'
    weight = 10
    title = "Rezepte"
    [languages.de.params]
      author = "Christian Plagens"
      description = "Eine Sammlung meiner Lieblingsrezepte."
      [languages.de.params.profile]
        # ... dein deutsches Profil ...
    # Menü für Deutsch
    [[languages.de.menu.main]]
      identifier = "cooking-de" # Eindeutige ID für den Hauptpunkt
      name = "Kochen"
      url = "cooking/" # Link zur Übersichtsseite "Kochen"
      weight = 10

      # --- Kinder von "Kochen" ---
      [[languages.de.menu.main]]
        identifier = "asian-de"
        name = "Asiatisch"
        url = "/de/cooking/asian/" # Vollständiger Pfad
        parent = "cooking-de"     # <-- HIER IST DIE MAGIE!
        weight = 10
      [[languages.de.menu.main]]
        identifier = "german-de"
        name = "Deutsch"
        url = "/de/cooking/german/" # Vollständiger Pfad
        parent = "cooking-de"
        weight = 20
      [[languages.de.menu.main]]
        identifier = "italian-de" 
        name = "Italienisch"
        url = "/de/cooking/italian/" # Vollständiger Pfad
        parent = "cooking-de"
        weight = 30

    [[languages.de.menu.main]]
      identifier = "baking-de" # Hauptpunkt "Backen"
      name = "Backen"
      url = "baking/"
      weight = 20
      # Hier könntest du später Kinder für "Backen" hinzufügen, z.B.
      # [[languages.de.menu.main]]
      #   name = "Kuchen"
      #   url = "/de/baking/kuchen/"
      #   parent = "baking-de"
      #   weight = 10

    [[languages.de.menu.main]]
      identifier = "dessert-de" # Hauptpunkt "Desserts"
      name = "Desserts"
      url = "dessert/"
      weight = 30
      # ggf. Kinder für "Desserts"

    # --- Andere Menüpunkte bleiben gleich ---
    [[languages.de.menu.main]]
      identifier = "search-de"
      name = "Suche"
      url = "search/"
      weight = 110
    [[languages.de.menu.main]]
      identifier = "tags-de"
      name = "Tags"
      url = "tags/"
      weight = 120

  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 20
    title = "Recipes"
    # Menü für Englisch
    [[languages.en.menu.main]]
      identifier = "asian-en" # Eindeutige ID
      name = "Asian"
      url = "asian/"
      weight = 10

  [languages.it]
    contentDir = 'content/it'
    languageName = 'Italiano'
    weight = 30
    title = "Recipes"
    # Menü für Italienisch
    [[languages.it.menu.main]]
      identifier = "cooking-it" # Eindeutige ID für den Hauptpunkt
      name = "Cucina"
      url = "cooking/" # Link zur Übersichtsseite "Cucina"
      weight = 10

      # --- Kinder von "Cucina" ---
      [[languages.it.menu.main]]
        identifier = "asian-it"
        name = "Asiatico"
        url = "/it/cooking/asian/" # Vollständiger Pfad
        parent = "cooking-it"     # <-- HIER IST DIE MAGIE!
        weight = 10
      [[languages.it.menu.main]]
        identifier = "german-it"
        name = "Tedesco"
        url = "/it/cooking/german/" # Vollständiger Pfad
        parent = "cooking-it"
        weight = 20
      [[languages.it.menu.main]]
        identifier = "italian-it" 
        name = "Italiano"
        url = "/it/cooking/italian/" # Vollständiger Pfad
        parent = "cooking-it"
        weight = 30

    [[languages.it.menu.main]]
      identifier = "baking-it" # Hauptpunkt "Dolci"
      name = "Dolci"
      url = "baking/"
      weight = 20

    [[languages.it.menu.main]]
      identifier = "dessert-it" # Hauptpunkt "Desserts"
      name = "Desserts"
      url = "dessert/"
      weight = 30

    [[languages.it.menu.main]]
      identifier = "search-it"
      name = "Ricerca"
      url = "search/"
      weight = 110
    [[languages.it.menu.main]]
      identifier = "tags-it"
      name = "Tag"
      url = "tags/"
      weight = 120
    [[languages.it.menu.main]]
      identifier = "asian-it" # Eindeutige ID
      name = "Asiatisch"
      url = "asian/"
      weight = 10
    # ... weitere italienische Menüpunkte
