baseURL = "https://gem-cp.github.io/recipes/"
languageCode = "de-de"
title = "Meine Rezeptsammlung"

# Theme als Modul importieren
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

# Sag Hugo, wo dein Inhalt und deine Bilder liegen
#contentDir = "content"
#staticDir = ["static"]

[outputs]
  home = ["HTML", "RSS", "JSON"] # Needed for search functionality

[params]
  author = "Christian Plagens"
  description = "Eine Sammlung meiner Lieblingsrezepte."
  defaultTheme = "auto" # "light", "dark" oder "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  EnableInstantClick = true

  [params.search]
    enable = true

  [params.homeInfoParams]
  Title = "Willkommen in meiner Küche!"
  Content = "Hier findest du eine Sammlung einfacher und leckerer Rezepte aus aller Welt. Viel Spaß beim Nachkochen!"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    identifier = "asian-menu"
    name = "Asiatische Rezepte"
    url = "/asian/"
    weight = 10
  [[menu.main]]
    identifier = "german-menu"
    name = " Deutsche Rezepte"
    url = "/german/"
    weight = 20
  [[menu.main]]
    identifier = "italian-menu"
    name = " Italienische Rezepte"
    url = "/italian/"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 100